### ISSUE TITLE
fail a CI job based on the threshold check

### ISSUE THREAD

**Issue by muratkeremozcan** [bahmutov/check-code-coverage#30]
We are looking for a hacky way to fail a CI job based bash output.

```bash
✅ Total statement coverage 95.68% is >= minimum 95%
```
If we do not see a ✅, fail the job. Is this possible?

**Comment by bahmutov** [comment]
What's the command that you are using right now? Something like this?

```
check-total --min 95
```

**Comment by muratkeremozcan** [comment]
> What's the command that you are using right now? Something like this?
> 
> ```
> check-total --min 95
> ```

`npx check-total --from combined-coverage/coverage-summary.json --min 95`

**Comment by bahmutov** [comment]
The above command will exit with non-zero code if the coverage is below your minimum, breaking the build

```
$ node bin/check-total --min 30
✅ Total statement coverage 100% is >= minimum 30%
[1]+  Done                    /Applications/Visual\ Studio\ Code.app/Contents/MacOS/Electron .
~/git/check-code-coverage on master
$ node bin/check-total --min 120
🚨 Statement coverage 100 is below minimum 120%
file /Users/gleb/git/check-code-coverage/coverage/coverage-summary.json
~/git/check-code-coverage on master
$ echo $?
1
```

**Comment by muratkeremozcan** [comment]
> The above command will exit with non-zero code if the coverage is below your minimum, breaking the build
> 
> ```
> $ node bin/check-total --min 30
> ✅ Total statement coverage 100% is >= minimum 30%
> [1]+  Done                    /Applications/Visual\ Studio\ Code.app/Contents/MacOS/Electron .
> ~/git/check-code-coverage on master
> $ node bin/check-total --min 120
> 🚨 Statement coverage 100 is below minimum 120%
> file /Users/gleb/git/check-code-coverage/coverage/coverage-summary.json
> ~/git/check-code-coverage on master
> $ echo $?
> 1
> ```

Brilliant, thank you!

This helps in the combined scenario where nyc threshold check only checks the Cypress coverage, but we still have unit test coverage to consider. And it works in any CI. Great stuff.
